apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-ecr
        image: 590183663006.dkr.ecr.ap-south-2.amazonaws.com/netflix:latest
        ports:
        - containerPort: 80
